server:
  port: 8888

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boot_vue_online_exam?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false&nullCatalogMeansCurrent=true
#    url: jdbc:mysql://localhost:3306/boot_vue_online_exam?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 19930919
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 10
  #activiti配置
  activiti:
    check-process-definitions: true
    database-schema-update: true
    async-executor-activate: false   # 是否打开异步执行器
    history-level: full

#mybatis配置
mybatis:
  config-location: classpath:mybatis-config.xml
  type-aliases-package: com.qxf.entity
  mapper-locations: classpath:mapper/*.xml


# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

#jwt
jwt:
  header: Authorization
  # 令牌前缀
  token-start-with: Bearer
  # 必须使用最少88位的Base64对该令牌进行编码
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  # 令牌过期时间 此处单位/毫秒 ，默认1小时（3600000）
  token-validity-in-seconds: 3600000
  # 在线用户key
  online-key: online-token
  # 验证码
  code-key: code-key


#spring.activiti.database-schema-update=true
#spring.activiti.check-process-definitions=true
#spring.activiti.process-definition-location-prefix = classpath:/processes/
#spring.activiti.job-executor-activate=false

#关闭activiti的定时任务
#spring.activiti.async-executor-activate=true
#
##    process-definition-location-suffixes:
##      - **.bpmn
##      - **.bpmn20.xml
#spring.activiti.history-level = full


#打印activiti执行的sql
#logging.level.org.activiti.engine.impl.persistence.entity.JobEntity=info
#logging.level.org.activiti.engine.impl.persistence.entity=trace